version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install Carthage Dependencies
          command: carthage bootstrap --use-ssh --platform ios
      - run:
          name: Run Tests
          command: bundle exec scan -s iOS -p Parchment.xcodeproj 
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
