osx_image: xcode9.2
language: objective-c

xcode_project: FoldingCell/FoldingCell.xcodeproj
xcode_scheme: FoldingCell
xcode_sdk: iphonesimulator11.2

# SWIFT_VERSION: 4.0

# whitelist
branches:
only:
- master
